requests:
  - url: "https://example.com"
    timeout: 30
    method: GET
    headers:
      User-Agent: "AWS Synthetics Canary"  # Will be replaced with actual canary user agent string
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    assertions:
      - type: STATUS_CODE
        operator: EQUALS
        value: 200
